### ISSUE TITLE
Course Review Section

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#1008]
- [ ] keep in mind this review was fill on the nation of a course which was done on a community and again created on the this same nation
* on community it works ...
- [ ] reviews made on nation of community stuff should be synced back

**Comment by Pr0chin** [comment]
https://files.gitter.im/open-learning-exchange/QA/9zz7/16-6.png

**Comment by Pr0chin** [comment]
![c](https://user-images.githubusercontent.com/24644003/29863518-a9b11ba6-8d8f-11e7-8014-123c895dee4d.png)

**Comment by Pr0chin** [comment]
![d](https://user-images.githubusercontent.com/24644003/29863530-b08e4584-8d8f-11e7-957e-a311e062614c.png)

**Comment by razu9861** [comment]
@dogi 
* Reviewing answers of community in nation
- review is possible but to send reviewed data to community is difficult because community doesn't have  public Url
- pulling from community can cause conflicts which one to pull first, pulling resent data can erase older reviewed data and progresses
@dogi regarding to this issue Laxman brother wants to have a word with you
