### ISSUE TITLE
Find out how to make BeLL-Apps work in firefox private mode

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#102]
... or find out why not

**Comment by SadiaRasheed** [comment]
It works in Firefox Private mode.

**Comment by dogi** [comment]
:)

@SadiaRasheed  Yes and No
it works only in parts ...

e.g. can't open a movie from the library

as next step we should collect more cases which are not working there

**Comment by MWakas** [comment]
I did research and got the following point:
-IndexedDB is completely disabled in the privacy modes of browsers (Private Browsing mode for Firefox and Incognito mode for Chrome). The whole point of private browsing is to leave no footprints, so attempting to open a database fails while in this mode.
As pouch db is also an indexedDB, that's why it will not work in private mode.
Here you can see more about this:
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB
