### ISSUE TITLE
Ability for Members to select a language

### ISSUE THREAD

**Issue by jstearnsw** [open-learning-exchange/BeLL-Apps#112]
We would like to add an enhancement that allows members the ability to select different languages for the pages on the BeLL (for example, they could have the option to switch between English and Urdu on every page)

How would you do this on every page?

How would this be done on just the dashboard page?

Any ideas on how to best implement this enhancement?

**Comment by SabaBaig** [comment]
--There is a suggestion from our side, that since the facility to select language should be the first one, before surfing through the whole website, so it is suggested that it should be on the login page (perhaps in the blue header bar, in the form of a drop-down) and finally it is also provided in the settings named as Configurations in both Nation and Community. In the form of Select Language from the set of currently available language.

**Comment by SabaBaig** [comment]
This facility is provided on the login page, since the facility to select language should be the first one, before surfing through the whole website, so it is suggested that it should be on the login page.
![l-1](https://cloud.githubusercontent.com/assets/13994879/10305730/811fd0c8-6c3b-11e5-88e8-9cfc5f79d99b.PNG)
Also, it is provided in the configurations page
![l-2](https://cloud.githubusercontent.com/assets/13994879/10305735/8a1ae442-6c3b-11e5-916f-1dd43e77545e.PNG)

**Comment by MWakas** [comment]
The current language field has been hidden.Here you can find changes in the code on github: 
https://github.com/open-learning-exchange/BeLL-Apps/commit/a2c587fbbd442f2325a22e4d7f651411672ccf5b
https://github.com/open-learning-exchange/BeLL-Apps/commit/d4565873a47980bcd89692fea8bb73cf2a93c9d6

**Comment by dogi** [comment]
please also preselect current language of available language

**Comment by SabaBaig** [comment]
This task is completed and here are the links for commit.
https://github.com/open-learning-exchange/BeLL-Apps/commit/018a97a3d2168c350ed7112a8fcd00f91cdddca5
https://github.com/open-learning-exchange/BeLL-Apps/commit/da1660f43869e30087fd1215a56394363d9c7a64
