### ISSUE TITLE
Pdf resource does not open

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#130]
Pdf resource does not open ( in library and on dashboard ) if you have opendWith = "PDF" while editing or adding resources

**Comment by SadiaRasheed** [comment]
Dev Team has tested this issue on older versions (versions before MUI) and it turns out that this is not Merge issue (MUI and dev) you can check it on earthbell too.

**Comment by MWakas** [comment]
Tested this issue on multiple versions(ole and new),its same at all versions(no matter with MUI or without MUI). Here are the steps to reproduce it:
![one](https://cloud.githubusercontent.com/assets/10882476/10881648/65d1dd24-8186-11e5-9f27-731463819227.PNG)
![two](https://cloud.githubusercontent.com/assets/10882476/10881650/701c74ec-8186-11e5-9f5c-2fd16984ed3c.PNG)
![three](https://cloud.githubusercontent.com/assets/10882476/10881655/7b19613e-8186-11e5-9fbc-6545d3e2e7a5.PNG)
Its also not working in My-Library at dashboard. Here are the steps to re-produce it from My-Library on dachboard.
![4](https://cloud.githubusercontent.com/assets/10882476/10881689/bd0bcf00-8186-11e5-8eee-2bd9f01b278e.PNG)
![5](https://cloud.githubusercontent.com/assets/10882476/10881690/bd22816e-8186-11e5-9a99-76dc4d213552.PNG)
![6](https://cloud.githubusercontent.com/assets/10882476/10881691/bd23eacc-8186-11e5-94af-4df9f9819e20.PNG)
It works when we select "Just Download" from media dropdown.It works from both locations(mentioned above):
Now we are solving it so that it also may work with PDF.

**Comment by SadiaRasheed** [comment]
Here are github links
https://github.com/open-learning-exchange/BeLL-Apps/commit/2454e8dc9abb4850936b91c362a830289c9ee7e0
https://github.com/open-learning-exchange/BeLL-Apps/commit/e81b58d843e67dcc87e784c388e9df88324415c3
https://github.com/open-learning-exchange/BeLL-Apps/commit/f300c34cdf1d9641a9b2ca2af771276e38585436

**Comment by SadiaRasheed** [comment]
This problem occurred due to updating the pouchdb version (5.1.0) to the latest version (2.1.0)

here are some screenshots describing the error

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/80d61bcee3d8724e9653568a7398f69af04ec4f5
