### ISSUE TITLE
MUI: Icons vanished from buttons

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#135]
Icons vanished from buttons on resources page in library

**Comment by SadiaRasheed** [comment]
![icons vanished](https://cloud.githubusercontent.com/assets/10362799/10937301/c34c9d98-8313-11e5-9356-1b391a5c7182.PNG)

**Comment by SadiaRasheed** [comment]
![course icon issing](https://cloud.githubusercontent.com/assets/10362799/10938057/1a0ae78e-8319-11e5-8f3f-79a0e9e0737f.PNG)

**Comment by SabaBaig** [comment]
This issue is resolved now, here are the commit links,
https://github.com/open-learning-exchange/BeLL-Apps/commit/51f8246890ec64b725bf57fda810a1ae68b7c7b6
https://github.com/open-learning-exchange/BeLL-Apps/commit/7dae606700fb1d38b598a5aaae6b7809f30c5938
https://github.com/open-learning-exchange/BeLL-Apps/commit/9fc8cce88aa772050cec935bf5b45aae6fa5dcd7
https://github.com/open-learning-exchange/BeLL-Apps/commit/9f7071341ac6a2321a8147c53e99fd7fc51f42ac
