### ISSUE TITLE
Username does not show up in dashboard

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#170]
compared to version 0.11.63 now we have a regression ;)
please also solve the undefined in Edit Member page

**Comment by SabaBaig** [comment]
This issue is solved now and here are the commit links,
-Missing UserName for Non-admin member is resolved)
https://github.com/open-learning-exchange/BeLL-Apps/commit/9bba2b7b8e87a808ff48e54998b8e23ce05089d6
-Undefined label corrected for Member/Edit
https://github.com/open-learning-exchange/BeLL-Apps/commit/8792533feedac5880cbd96bc9abdced04aad1667
-Resolved MUI Errors on Edit Member page
https://github.com/open-learning-exchange/BeLL-Apps/commit/59648346e769643d72bdbabba0b55f536f941807

**Comment by SabaBaig** [comment]
Correction in workflow for Nation
https://github.com/open-learning-exchange/BeLL-Apps/commit/0a074b35a24818b0b155076416861947f0ca6913
