### ISSUE TITLE
MUI for publication page

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#173]

**Comment by SabaBaig** [comment]
I tested this issue on both tablets provided by OLE-Team and also specifically tested on small device resolutions through firebug for English and Arabic. In either way, I could conclude that no contents go out of the page bounds when you zoom-in instead there is a scroll bar on the bottom. On tablets, you can slide to the right/left side of the page in order to see the hidden contents.
See the attached screen-shot,
![untitled](https://cloud.githubusercontent.com/assets/13994879/12291996/4b521ebe-ba0c-11e5-9781-98f2e9ecbbfc.png)
But in case of still facing the same problem, then please provide us essential details like,
  --Device being used for testing; e.g Tablet/Laptop etc
  --Its device resolution.

**Comment by SabaBaig** [comment]
Need more information to solve this issue, like device resolution specially. As, its still not appearing on my side.
