### ISSUE TITLE
Form fails to submit on Non-English Inputs

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#174]

**Comment by SabaBaig** [comment]
I tested this issue by providing Urdu characters as input on Add Member form and later on logged into system by using those credentials. For this purpose, I have been using Firefox and Windows machine. I changed the default behavior of English Qwerty keyboard to be used for Urdu as well. I'm unable to reproduce this bug. Please provide us more details.

**Comment by EmilyLarkin** [comment]
So I'll do my best to explain, but if something is unclear, please let me know. First off, the function works in English completely fine. But at the very beginning of the login process, if you switch your language to Arabic and then attempt to become a member, you end up with this page:
![screenshot_2016-01-14-19-13-30](https://cloud.githubusercontent.com/assets/15271637/12335724/4b558eca-bb09-11e5-80ef-57209290760d.png)
![screenshot_2016-01-14-19-13-39](https://cloud.githubusercontent.com/assets/15271637/12335742/59b339ae-bb09-11e5-97fb-e31be5f449ef.png)
At the top, it says "undefined" and all of the words are in English. Rory and I could've both sworn that this page used to work and be in Arabic. Perhaps we are wrong, but I would strongly say that I remember it in Arabic previously. The real problem is that when you click submit after filling out the form, the "Register" button in unclickable and does not result in anything. While the screen looks exactly the same when registering in English (including the undefined bit), the "Register" button is clickable and does successfully create members. In contrast, in Arabic it does not. You can log in under Arabic language once it has been created, but creating it in Arabic is the problem. And in regards to the language and keyboard settings on the tablets, it doesn't matter: we used Arabic keyboard with English tablet, English keyboard with Arabic tablet, and every other combination under the sun as I assumed that you would ask this so I had them test it out. It doesn't make a difference (the only thing that makes a difference if you try to register with a password in Arabic script- it doesn't allow that login although everything else can be in Arabic). Please note this was all done on the localBeLL, which makes troubleshooting more difficult.

**Comment by SabaBaig** [comment]
The word undefined was resolved from https://github.com/open-learning-exchange/BeLL-Apps/releases/tag/0.11.90 onwards

**Comment by dogi** [comment]
@SabaBaig: jupp parts of stuff you already fixed came also from @EmilyLarkin ;) 
Anyway I also was not been able to reproduce this bug of not been able to commit in the non-English form ...
Also 0.11.91 has passed QA and syriabell was updated today, so that the Communitybells in Jordan can be updated. Please @EmilyLarkin update and retry.

**Comment by SabaBaig** [comment]
yes thanks to @EmilyLarkin for her efforts in Arabic :)

**Comment by EmilyLarkin** [comment]
Of course- anytime!

On Mon, Jan 18, 2016 at 11:50 AM, Saba Baig <notifications@github.com>
wrote:

> yes thanks to @EmilyLarkin <https://github.com/EmilyLarkin> for her
> efforts in Arabic :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-learning-exchange/BeLL-Apps/issues/174#issuecomment-172481269>
> .
>



-- 
Emily Larkin
Project Manager- TIGAR Project
emily@ole.org

Open Learning Exchange, Inc. (OLE)
One Broadway, Cambridge MA 02142, USA
www.ole.org
