### ISSUE TITLE
create languages.md

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#176]
describe in there the structure of language files, so that future translations are easier done

**Comment by SabaBaig** [comment]
This issue is resolved now and the markdown file in located in init_Docs folder with the name of "languages_guideLines.md" for future reference. Please follow the provided GitHub commit links,
--Create languages_guideLines.md 
https://github.com/open-learning-exchange/BeLL-Apps/commit/48d245d5be29b6eaa29698460515715df9927bdf
--Added images folder for languages.md
https://github.com/open-learning-exchange/BeLL-Apps/commit/4f423b7d7187be46ffba1dde053a614a1de424a4
--Updated the images and text in languages_guideLines.md
https://github.com/open-learning-exchange/BeLL-Apps/commit/a6405d2ee789fa266a1505b29c5ff5d45a0f34b6
