### ISSUE TITLE
delete publication has no abort

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#180]
once clicked

![deletepage](https://cloud.githubusercontent.com/assets/13684059/12572826/2fc57094-c3bf-11e5-9971-07c0a4fd7523.PNG)

there is no way out

![deletepage1](https://cloud.githubusercontent.com/assets/13684059/12572832/42fb39fa-c3bf-11e5-91dc-fbe16ee6c7e2.PNG)

**Comment by SabaBaig** [comment]
This issue is resolved now 
# For Publications
![capture](https://cloud.githubusercontent.com/assets/13994879/12580310/3e4403a6-c450-11e5-8e64-bded9ccff0f8.PNG)
and similarly, corrected for **Survey** Functionality as well. 

GitHub Commit links,
**Publications** : https://github.com/open-learning-exchange/BeLL-Apps/commit/3644567e1ff770840f8619e8a18f767884a083a4
**Survey** : https://github.com/open-learning-exchange/BeLL-Apps/commit/3b1a4af337b862f5122dbf2c1fb99007c36a8b89

**Comment by SabaBaig** [comment]
# For Reports
https://github.com/open-learning-exchange/BeLL-Apps/commit/e780f820166e8b1e39ba5ebe68616851f87a33d4
