### ISSUE TITLE
MUI: fix Dialog boxes

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#184]

**Comment by dogi** [comment]
a Dialog box is needed during it's software upgrade which on the its update will be "undefined"

**Comment by SabaBaig** [comment]
**GitHub Commit Links**
https://github.com/open-learning-exchange/BeLL-Apps/commit/11f6bca8714ed1ddc83bece6b0cbb70c72dcd72e
https://github.com/open-learning-exchange/BeLL-Apps/commit/cd4758b5710b24cf5615ac2f3aedcb86f27475bc
https://github.com/open-learning-exchange/BeLL-Apps/commit/c38dfcb14c3b017d8c870bd08274c1e23e4233a4

**Comment by SabaBaig** [comment]
Tested the issue of "OK" button on alert messages on "Firefox Arabic Version" and since, its the default message based upon the underlying browser hence, its according to its default language.
![capture](https://cloud.githubusercontent.com/assets/13994879/12886054/b4b7dc74-ce8c-11e5-9f84-3cec54f7dfe9.PNG)
![capture1](https://cloud.githubusercontent.com/assets/13994879/12886137/1a0a845a-ce8d-11e5-9015-b15818bca4a8.PNG)

**Comment by dogi** [comment]
How to get arabic firefox ...
 - laptops: https://www.mozilla.org/en-US/firefox/all/
 - tablets: https://www.mozilla.org/en-US/firefox/android/all/

**Comment by SabaBaig** [comment]
- MUI: Updated message on dialog boxes for Reports
https://github.com/open-learning-exchange/BeLL-Apps/commit/2771af6ce1af50bcffa2667b10178c1f29058961

**Comment by SabaBaig** [comment]
-MUI: fix Dialog boxes for Nation
https://github.com/open-learning-exchange/BeLL-Apps/commit/3e55dac1f8d008af899fbd1e4a744b5b9d84c4e3
