### ISSUE TITLE
Dropdown menu of language is only in English

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#198]
English, Arabic, and Urdu are all in English, where as both Arabic and Urdu should be in Arabic script so that learners in the field who don't know English characters can select their language.

See below. 

![screen shot 2016-03-04 at 5 00 41 pm](https://cloud.githubusercontent.com/assets/15271637/13542271/849ded10-e22f-11e5-8ae9-104addd6f005.png)

**Comment by SabaBaig** [comment]
This is due to the fact that in every document we store the name of language in native language and currently it's provided in English only. So when we'll replace these from there, this will be resolved. Please see this screenshot.
![capture](https://cloud.githubusercontent.com/assets/13994879/13561112/b8b6cdca-e44a-11e5-856f-81abf5e012c4.PNG)
For more reference, please visit this link,
[ Read BeLL-Apps/init_docs/languages_guideLines.md](https://github.com/open-learning-exchange/BeLL-Apps/blob/dev/init_docs/languages_guideLines.md)
