### ISSUE TITLE
make search resiliant against old (e.g. without all attributes) resources

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#221]
search on openbell is really often not compleating because javascript is crashing, it looks like the cause for this are older resources

**Comment by EmilyLarkin** [comment]
@umarWaris @MWakas @SabaBaig I used to be able to replicate this bug if I click quickly back and forth between the search and the library. I would login, go to library, go to search, search for any resource, open the resource, and then return to library and search again. If I repeated this pattern two or three times (library, search, open), I would freeze the search function and have a continuous spinning loading wheel (javascript was crashing). However, due to some changes on openBeLL, I can't replicate it right now as it seems to not crash the javascript. I'll update you if I can give you a clear path to replication.

**Comment by SabaBaig** [comment]
Thanks @EmilyLarkin  will try to follow the same steps to recreate the bug at our side.

**Comment by dogi** [comment]
maybe recreate with resources with missing attributes

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/73c93792bafcdc44ded5dfe43e55dcdf6e57f4de
