### ISSUE TITLE
Courses | All the leaders of a course should be able to manage that course

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#257]
- Make sure all leader(s) specified for any course can manage that course

**Comment by SadiaRasheed** [comment]
Multiple leaders of a course are now able to manage that  course 
https://github.com/open-learning-exchange/BeLL-Apps/commit/8fac89b2cdc4cb5cad41d5144cefb7aac4e0547c

**Comment by SadiaRasheed** [comment]
Multiple leaders should be able to see the progress of a course.

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/db6d117c84696745e6f4dd1d15267b94a9488f9f

**Comment by SabaBaig** [comment]
@dogi Can you please guide us how the progress of any member(including leaders and creator) was managed in courses?
Since, it is creating a problem when you add course step and then delete them. The ones who were added before the deletion of step are not updated but the afterwards added new members get updated course steps and hence maintain their progress accordingly.

---

Also, Please tell us how the visibility of course progress is handled?
Like, who can see whose progress?? and how it gets gradually updated.

**Comment by SabaBaig** [comment]
Until now the implementations are on following Github Commit links against Course Progress,
https://github.com/open-learning-exchange/BeLL-Apps/commit/de43e9a9a11eea4be29fd861ca6402f5f2dc4464
https://github.com/open-learning-exchange/BeLL-Apps/commit/73c9552f04fa4f4a836b55886807f8e64b8d0e09

**Comment by SabaBaig** [comment]
Member progress revisited to solve 
[Related to Issue#271](https://github.com/open-learning-exchange/BeLL-Apps/commit/b56fd70776d448f829e09883a86400b5d3b21118)

**Comment by EmilyLarkin** [comment]
Tested and looks great after previous issue was closed
