### ISSUE TITLE
Course | Correct the "Paper Progress"

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#299]
The orientation of papers submitted against any step should be corrected. The paper submitted should appear underneath the leader/learner who submitted it.
![Issue#299](https://cloud.githubusercontent.com/assets/13994879/15777079/25b402d0-29a6-11e6-95b5-17abfb40744b.png)

**Comment by umarWaris** [comment]
For learner, progress page

![capture](https://cloud.githubusercontent.com/assets/17467658/15926648/aa016d84-2e56-11e6-99b2-f4a2b56d0523.PNG)

For Leader. Progress Page

![capture](https://cloud.githubusercontent.com/assets/17467658/15926695/f99ecada-2e56-11e6-8337-60f98670c798.PNG)

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/15956270/c9345cca-2f00-11e6-8bea-816b09de3c67.PNG)

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/15961438/3172997e-2f1e-11e6-90d7-d4cbd66377db.PNG)

As the graphs are much small, so we can't show drop down against each member

**Comment by umarWaris** [comment]
-each line shows paper submitted against steps for each member from left to right i-e the steps for paper of first member are on the first line
-if any member has not submitted any paper against any step, then the line number of that user is skipped and hence can be mis-understood as which line belongs to which member.
-we can't put buttons or drop-down underneath the member's graph because if there are too many members then the size of drop-down or button would be too small and its text would not be readable.
@dogi @EmilyLarkin

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/d4b1892763b3b3edcc426f97d85f32aec97d686b

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/8367b749bb9fad3bcab8b4327a6de1e6c4a6222b

**Comment by EmilyLarkin** [comment]
I think we should consider other options for this problem as the current solution doesn't really seem workable. @dogi, do you think a separate pop-up screen is a bad idea. Looking for us to problem-solve on this issue a bit more....

**Comment by EmilyLarkin** [comment]
@umarWaris @SabaBaig this should be revisited as part of Badges edits in courses- connected to issue #289
