### ISSUE TITLE
easy install | _security problem on center?

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#362]

**Comment by MuhammadWaqas05** [comment]
I tested the following scenarios on my side:
- Enable _security on requested nation db too(same as for central nation db)
   Findings: This scenarios didn't work on my side, as the result was same as before.
- Disable _security on central nation db  
   Findings: This is working fine(pulling and pushing is successfull). As the result was fine and working properly, so I made required changes so that the functionality of easy install can work smoothly.
