### ISSUE TITLE
Reorder language dropdown menus alphabetically

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#40]
Reorder the language dropdown menus for both the Add A Resource page and the Configurations Form.

Arabic 
Asante 
Chinese 
English
Ewe 
French 
Hindi 
Kyrgyzstani 
Nepali 
Portuguese
Punjabi 
Russian
Urdu
Somali
Spanish 
Swahili

**Comment by MWakas** [comment]
This issue was solved.Here are the screenshots of the required pages: 
![lang_config](https://cloud.githubusercontent.com/assets/10882476/9518169/185e042e-4cce-11e5-886b-44d49c51c322.png)
![lang_res](https://cloud.githubusercontent.com/assets/10882476/9518168/185de048-4cce-11e5-8454-fa042243fd0f.png)
