### ISSUE TITLE
Deleting Collections: Keep Resource, Remove Collection Name

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#41]
When deleting a collection, the Collection name was still listed in the library even after refreshing the page.

[add screenshot]

Note: When a collection is deleted we would like the collection name to be removed from the Collection dropdown menu and from the main library page.  But we want the resource(s) associated with that collection to remain as part of the library.

**Comment by SadiaRasheed** [comment]
It has been completed and it was included in September 18, 2015 release.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/issues/41

**Comment by SabaBaig** [comment]
Previous Commit https://github.com/open-learning-exchange/BeLL-Apps/commit/52906c98b63f764329c4229fcc7993319554e486

**Comment by SabaBaig** [comment]
Initial Commit https://github.com/open-learning-exchange/BeLL-Apps/commit/b34fdca36b337aada8589328f5a6b53896c5ec5a

**Comment by jstearnsw** [comment]
I tried in the community:
- I created a new collection called test
- I created a new resource called a
- I added resource 'a' to collection 'test'
- I confirmed that this happened by switching back to resources and checking to see that 'test' was displayed for the resource's collection
- I deleted collection 'test'
- I went back to the main library page and clicked 'Add New Resource' to check if 'test' had been removed from the collection drop-down menu (success)
- I went to the main library page to confirm that resource 'a' was not deleted when collection 'test' had been deleted (success)

This is where I noticed that 'test' was still displayed on the main library page as resource 'a' collection (see screenshot):

Is the collection still supposed to be listed for the resource on the main library page after it has been deleted?

I did not test this on the nation because I found a different bug:
https://github.com/open-learning-exchange/BeLL-Apps/issues/108

**Comment by SabaBaig** [comment]
I am unable to generate this issue at my side, please provide me with more details.

**Comment by SadiaRasheed** [comment]
@jstearnsw : What version of Bell apps do you have on your community and nation?

**Comment by SabaBaig** [comment]
From debugging on an old-community (having version less than 61), it is observed that one of the views (resourceOnTag) required for this task is not synced to couchdb. We need to update the community and its corresponding nation to upgraded nation to avoid this issue.

**Comment by jstearnsw** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/issues/108 duplicate issue
