### ISSUE TITLE
Community: Become a community form check for double names/codes

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#476]
There are three test cases
1) Fresh install (and upgrade from older version)
2) updating(nation is changed)
3) updating(name and/or code is not changed)

**Comment by umarWaris** [comment]
@dogi Please add description for each scenario

**Comment by SadiaRasheed** [comment]
Requirements for this issue are not clear. Please elaborate a little bit more so that I can understand.
- If there is a community on central nation with the same name and same nation as your community then it should prompt user to change the name? or what? 
- It should check the central nation for community name , code and nation url and if match found then configuration doc should not be replicated to central nation and should show user that community is already registered?? 
  I need explanation for theses points

**Comment by SadiaRasheed** [comment]
what I did so far.
           -When user clicks on register, A request is sent to the central database which get those documents having the same community name as entered by user.  And then what should it do?

**Comment by SadiaRasheed** [comment]
What have been implemented so far?
Duplicate Name Finder
              Whenever user clicks on Register on configurations page, system will check on Central database whether this community name , code already exist for the same nation or not. If exists it prompts user to choose another name.

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/edf0b1b156a419e8d1f8237f3cb8b29fa6197d75

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/711c0b5a469e055529b39748587b256c2dfce5dc

**Comment by dogi** [comment]
in configurations form - allow changes when same name and/or code when document has same id this community

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/4ca3c4f99243605b0de233ab85d46162c0cadf00

**Comment by SadiaRasheed** [comment]
Part1: Community: Become a community form check for double names codes
  Part2: Highlight duplicate name or Code to the User
  Part3: update Community information including name and code both on nation and community.
 Part4: Highlight code and name at the same time to check duplicate entries
