### ISSUE TITLE
Publications: On Nation, See Issue No. Each Community Successfully Downloads 

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#48]
One of two possibilities (not sure which way to go yet): 
1) Select a community and see which publications were successfully downloaded vs not successfully downloaded
or
2) Go to publications and see which community successfully downloaded vs not successfully downloaded

Keep in mind that there also needs to be a way to identify which communities have been sent which publications

**Comment by MWakas** [comment]
This issue is related to issue#101. As issue#101 is implemented recently(version# 0.11.80), so it will be easy to solve this one.
Here is the strategy we can use:
-There will be a new column at nation publications page named as "Downloaded By".
-When a community successfully downloads a publication(issue#) then the name of that particular community will be displayed in "Downloaded By" column.
Please share with  us your views in this regard.

**Comment by MWakas** [comment]
This issue is resolved.Here is the screenshot of the solution:

And here is the link of commits on GitHub:
https://github.com/open-learning-exchange/BeLL-Apps/commit/44a5875954f0f1e275b989d42bee181298171c70
https://github.com/open-learning-exchange/BeLL-Apps/commit/9439e819a789c07cacc45be1e90cd359505654e5
