### ISSUE TITLE
Upload Software/App as a Resource to the BeLL (javascript apps)

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#49]
Be able to upload javascript apps (i.e., turtleblock) to the BeLL and run within an internet browser.

examples:
turtle.sugarlabs.org
https://github.com/walterbender/turtleblocksjs

**Comment by SadiaRasheed** [comment]
It should be downloaded and then it should run in the browser after installation. right? I am going to test this on my machine

**Comment by dogi** [comment]
nope it should run out of couchdb

maybe it should say "Transform this html5 app into a couchapp"

**Comment by dogi** [comment]
important here is to develop a general way/recipe how to transfrom a html5 into a couchapp

**Comment by SadiaRasheed** [comment]
Thanks for clarification.

**Comment by dogi** [comment]
I would split this into steps:
- [x] bring app into couchdb with couchapp
- [x] write manual how to do step above
- [x] think/experiment about how to place html5 app in bell
- [ ] abstract manual how to bring html5 apps into bell

**Comment by i5o** [comment]
Imported turtleblocksjs to couchdb // First try.
Working on the manual on how to import apps.
-----

#### Porting TurtleJS to CouchApp
Needs

* Virtualbox  https://www.virtualbox.org/wiki/Downloads
* Vagrant https://www.vagrantup.com/downloads.html


```

git clone https://github.com/dogi/ole--vagrant-bells/ vagrant-vm
cd vagrant-vm/release
# add config.vm.box_version = "8.2.1"
vagrant up
# Download and install couchapp
git clone https://github.com/couchapp/couchapp.git 
cd couchapp
python setup.py build
sudo python setup.py install

```

[Reading](https://couchapp.readthedocs.org/en/latest/couchapp/gettingstarted.html)

### Creating a test ´couchapp´ app
```
$ couchapp generate turtlejs

$ tree -a turtlejs
turtlejs
├── .couchappignore
├── .couchapprc
├── README.md
├── _attachments
│   ├── index.html
│   ├── script
│   │   └── app.js
│   └── style
│       └── main.css
├── _id
├── couchapp.json
├── language
├── lists
├── shows
├── updates
├── vendor
│   └── couchapp
│       ├── _attachments
│       │   ├── jquery.couch.app.js
│       │   ├── jquery.couch.app.util.js
│       │   ├── jquery.couchForm.js
│       │   ├── jquery.couchLogin.js
│       │   ├── jquery.couchProfile.js
│       │   ├── jquery.mustache.js
│       │   └── md5.js
│       └── metadata.json
└── views
    └── recent-items
        └── map.js

11 directories, 18 files
$
```

```
.couchapprc content
{ 
    "env" : {
        "default" : {
            "db" : "http://localhost:5985/apps"
        } 
    }
}
```

```
$ cd _attachments
$ rm -rf *
$ git clone git://github.com/walterbender/turtleblocksjs turtlejs
$ mv turtlejs/* .
$ rm -rf turtlejs
$ couchapp push default
2016-01-12 22:56:40 [INFO] Visit your CouchApp here:
http://localhost:5985/apps/_design/turtlejs/index.html

```

**Comment by i5o** [comment]
![captura de pantalla 14](https://cloud.githubusercontent.com/assets/2650479/12283554/16655436-b986-11e5-82db-898f9b6192cc.png)
![captura de pantalla 15](https://cloud.githubusercontent.com/assets/2650479/12283555/16694280-b986-11e5-959e-ff6b4999130d.png)

**Comment by dogi** [comment]
awesome ;)

**Comment by i5o** [comment]
Here is the manual/tutorial, I would like to know if it's ok?

https://github.com/i5o/couchapp-port/blob/master/port.md

**Comment by rjsteinert** [comment]
Nice! turtlejs as a CouchApp! Now time to figure out how to get the BeLL App to recognize a CouchApp as an application that can be fed a BeLL Resource. This can be expressed in the following Use Cases.

- User clicks "Create new resource", selects Turtle Art, and then Turtle Art App opens with blank slate.
- User works for on new Turtle Art Resource in the Turtle Art App, clicks "Save", and then sees the Turtle Art Resource they just created in the Resource List.
- User clicks "edit" on a Turtle Art Resource, Turtle Art App opens with that Turtle Art Resource loaded; User modifies the Turtle Art Resource using the Turtle Art App and then clicks "save". 

In the past, Use Cases like these for other apps have been solved by including the App code in the BeLL Apps couchapp and then hard coding a bunch of things in the BeLL Apps codebase so that it knows how to load resources into the new App. The App also has to be modified to feed data (resources) back out to the BeLL App resources database. That is one architecture. Another idea would be to not have to hardcode recognition for new content types and apps into the BeLL Apps code but instead create a standard for how Apps can describe themselves to the BeLL Apps code. That way, some installations could have some apps, some installations could have others.

**Comment by i5o** [comment]
Yay!, Your ideas have sense, I think I will try to implement them.

[I already have a version that can load/save projects to the couchdb](https://github.com/ignauy/turtleblocksjs/tree/couch), so maybe we should remove the planet (where you can load the projects that are saved in the server), and save/load projects and find a way to list the projects as resources?

Also the projects will be available for all users.. What will happen if someone edits the project of another user? (this is possible currently in turtlejs...)

I want to know if ¿it's a problem that turtlejs only will be capable to work when connected to server?
What I mean is that turtlejs can be downloaded, but its not just a ".html" file, its needs a lot of other stuff (libs) to run.

This is just turtlejs, all this process will be  different for other apps, so I don't think we can make a manual for all apps, just for turtlejs that could be taken as a reference.

--
Sorry for my bad english  :dancer:

**Comment by rjsteinert** [comment]
Dogi says that creating new resources and editing them can come later. For now we could figure out how to just launch Turtle Art from the BeLL and not worry about saving. The goal he would like to be is the ability to see a resource in the library, click "open", and then the browser be redirected to the URL of that App. 

I think a new type of BeLL Resource called "URL" would be a good fit. The new resource type would contain a URL that when opened, would direct the user's browser to that URL. The trick is figuring out how to add a new BeLL Resource Type. It's been a long time since I've touched this codebase and I cannot see where this is added.

**Comment by MWakas** [comment]
GitHub commit link for "Open only latest attachment of resources":
https://github.com/open-learning-exchange/BeLL-Apps/commit/e23820dd7412238c869a9f59748fcb9b10331b55

**Comment by i5o** [comment]
Hello? D: I don't remember what I was supposed to do

**Comment by dogi** [comment]
You are doing it already https://rawgit.com/i5o/i5o.github.io/htmlresources/ll_CC/#!pages/htmlresources.md
