### ISSUE TITLE
Look into adding html resources to couchdb via Javascript/HTTP

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/BeLL-Apps#607]
Right now we use a [round about method](http://open-learning-exchange.github.io/#!pages/htmlresources.md) to get html apps into BeLL/Couch. It would be nice if users could select a folder containing a html app and add it to bell without having to use or know about couchapp. Since CouchDB supports HTTP, and there are already CouchDB wrappers, this should be possible. Essentially we just need to duplicate some of the functionality of CouchApp in javascript. If anyone has information or ideas on how we can go about doing this, please comment.

**Comment by paulbert** [comment]
@waryhermit @dogi Before I go too far on the wrong path, is the intent to incorporate this into the `resource/add` view within the BeLL-App?

There is a solution that I think would make that work, but it will only work for Firefox & Chrome and is non-standard.  I think it is the only solution that will currently allow a full directory upload via a browser, though, otherwise you would have to select each file one by one.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory

**Comment by waryhermit** [comment]
What if they zip it first maybe?

**Comment by paulbert** [comment]
Ok I found what looks like a decent solution for working with zipped files here: https://stuk.github.io/jszip/

The simple way to do this would be to unpack the zip when added and add all the files like a normal resource, but in the hangout @dogi mentioned this might not be the best solution because it would show a notification for each file when added to a RasPi (correct me if I misunderstood).

Here's what I'm thinking for the flow to solve that:
1. User inputs as HTML resource from Add New Resource with additional form field "Entry Point" which is the "index.html" or "main.html" file that the app loads from.
2. That zip gets unpacked and added locally uncompressed as normal, but the zip file is also added with a flag identifying this as an HTML resource/compressed.
3. When it's pushed to the nation, only the zip file is sent to the nation.
4. When an HTML resource is downloaded a script is run to unpack it before adding it to the local couchdb ensuring that the entry point file is the first in the _attachments array of the resource document.
5. (optional) To save space on the RasPi we could then delete the zip.  If we want top be able to push back to nation from the RasPi then we could write a script which would compress the files again before pushing to the nation.

Would that work?  Does that make sense?  Still learning how couchapps work so let me know if this is the wrong direction.

**Comment by waryhermit** [comment]
@paulbert @dogi @leonardmensah  The notification problem could also be solved from the andriod app end.

**Comment by dogi** [comment]
@paulbert thanks
@waryhermit good question
@leonardmensah do you think you can do that in the app?

**Comment by waryhermit** [comment]
This was fixed by #774
