### ISSUE TITLE
Duplicate resources appear in library when Next or Back buttons are clicked

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#70]
When having clicked through to the collections page where resources are viewed, it appears all resources are listed on one page. There is still a next button at the bottom of the screen and when clicked it just seems to duplicate the same resources that have already appeared on the screen in alphabetical order. 

After choosing a collection, there is BACK button at the bottom of that list that should take you back to the original master list.  It does not work.

**Comment by SadiaRasheed** [comment]
Could you please attach a screenshot where the problem is 
What I have perceived from the description is that when you go to the Library and then you click on collection. The collections are listed and when you click on a collection the resources are listed and if you click back button you cant go back to the collection page
![issue 70](https://cloud.githubusercontent.com/assets/10362799/10043801/41a244b6-620f-11e5-99e4-c6979a4b2645.PNG)
![issue70b](https://cloud.githubusercontent.com/assets/10362799/10043922/13edb9aa-6210-11e5-854d-3d67479bd327.png)
Moreover when you click on back button the  same resources re-appear
![issue70c](https://cloud.githubusercontent.com/assets/10362799/10043990/7c8e664e-6210-11e5-90e9-34dfa9ed8438.png)
Please verify this info so that I can review this Issue again and give you estimation.

**Comment by SadiaRasheed** [comment]
This problem is occurring at nation level too
![70-1](https://cloud.githubusercontent.com/assets/10362799/10220767/28e4a888-6863-11e5-9d40-74921296e9ca.PNG)

**Comment by SadiaRasheed** [comment]
BACK button is working on community level.
Need to test it on nation level too

**Comment by SadiaRasheed** [comment]
This Issue has been resolved at nation too

**Comment by SadiaRasheed** [comment]
Steps to test this issue
-1 open Bell Apps
-2 Click on Library
-3 Click on Collection
-4 Click on any collection e.g.,
- 5 Click on Back e.g.,
-6 BACK button won't work and will repeat the resources

**Comment by SadiaRasheed** [comment]
Github commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/ab4f1726562b58430de329645daee9574da27f78
