### ISSUE TITLE
Center: firewalled community still says registered even that is not happening

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#782]
the installing user sees 

![104-1](https://cloud.githubusercontent.com/assets/13684059/25612697/acbee408-2ef9-11e7-8f30-b04fbd133f3c.JPG)

and locally 

![104-2](https://cloud.githubusercontent.com/assets/13684059/25612739/c9427f22-2ef9-11e7-809a-5d2863092501.JPG)

but nothing happened on center ... no in couchdb and not in their logs

**Comment by dogi** [comment]
for example McAfee

**Comment by lmmrssa** [comment]
It was using replication so that could be the case as it might return some response empty or anything else when request is sent unless it gets some error code.
It is mentioned there is **'_replication_state'** to check the status of replication which will be **'completed'**, **'triggered'** or **'error'**. So will have to try checking it.

**Comment by dogi** [comment]
@lmmrssa awesome

**Comment by nirojdyola** [comment]
checked the reponse and displayed alert message "Unable to replicate apps." if it can not write in db.
