### ISSUE TITLE
Change layout of Communities page on nation

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#83]
When logged into nation as a manager and on the Communities page:
- swap the location of the following two columns: "Last Activities Sync" and "Last Publications Sync"
- add a second row for the Communities page headers so that more columns can fit (i.e., instead of having the text for Last App Update all on one line, it would wrap around to a second row and probably Update would be on the second line)
- remove the "-Name" at the end of Community-Name header
- add a column to the left of the Actions column called "Total Member Visits This Month"
- add a column to the right of the newly added column above (Total Member Visits This Month) called "Total Resource Views This Month"
- "Total Member Visits This Month" column should be pulled from the number that is shown on its respective trend report graph in the Total (orange) location
- "Total Resource Views This Month" column should be pulled from the number that is shown on its respective trend report graph in the Total (orange) location

**Comment by MWakas** [comment]
-The first five points are related to the layout,so we can call this as sub-task named as community-page-layout.
-The last two points are related to fetching data from trend reports,it can be called as community_page_data_work.
-The sub-task community_page_layout can be done in couple of hours.
-The community_page_data_work is complex as I analyzed it.So it can take time as it is also dependent on the completion of issue#80.

**Comment by MWakas** [comment]
The issue is completed.Here are the screenshot of the communities page on nbsbell-qa nation:

And here you can find the changes in the code on github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/46c81d1eb58dfcd42f37bae49e8f546d8bcd6921
https://github.com/open-learning-exchange/BeLL-Apps/commit/86e6d25fd4cd1d9e90fcb9556c4f072e4286aa8d
https://github.com/open-learning-exchange/BeLL-Apps/commit/876ee5e49e893969aa783718d779a7e02550f180
