### ISSUE TITLE
Search Error: Searching for resources on nation is broken

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#90]
During QA of releases beyond v0.11.52 (up to current version: v0.11.57), resources have not been able to be searched using the updated search feature.  For v0.11.57, we searched the resources that Dogi always includes when he installs a new nation (resources from openbell) and none of them could be found when we search keywords or select drop down menu items.  We then uploaded new resources by using the usual library form interface and then also tried adding a new document in the _utils interface, but we also had the same result: no results.

This is a big problem because we cannot send publications from nation to populate a new QA community since the publication couldn't get populated.

**Comment by jpierce7** [comment]
NBS was able to resolve this problem by having us re-update the nation with the same version (v0.11.57, in this case). NBS noticed that not all of the design docs were appearing in the newly installed nation but after updating the nation with the same version, the search worked and all of the design docs were there.

**Comment by MWakas** [comment]
I managed a session with Stephan regarding this issue.We found the root cause of that issue and discuss the future step to avoid the issue as well.The issue were not on our side.No problem with the code, version# or anything else on our side, that's why we didn't face and we couldn't reproduce the issue on our side.The QA team faced the issue because there was some problem with one of the steps they follow after installing the new nation.The details of that step are as following:
-Firstly they installed a new nation in which there were no missing scripts and everything was fine as it should be.
-Then they pushed some databases from a nation to this newly installed nation.This is the step where they generate the issue on the nation.When they pushed some databases from one nation to another, the databases of the source nation replace the databases of the target nation.As the databases replaced, the design_docs(which containing the views also get replaced). This issue arises when the version# of source nation is different than the version# of the targeted nation.The nation they were using as the source was on the version 0.11.52(before new search_feature) and the target nation was on the version 0.11.57(new search_feature),the old design_docs(older set of views) replace the new design_docs(new set of views which are related to the new search feature). In result of it the functionality of the new search_feature breaks.
Here are the screenshots of design_docs with complete and missing scripts respectively.
![without missing script](https://cloud.githubusercontent.com/assets/10882476/9682446/2c673c80-5320-11e5-8043-155749a09410.PNG)
![missing_scripts](https://cloud.githubusercontent.com/assets/10882476/9682457/3b8d416e-5320-11e5-8875-5d3d90f8e9ef.PNG)

We also discussed the procedure to avoid this problem.As they told us that its necessary to push databases from source nation to the newly installed/updated nation, we decided that we will write a script of replication which will push only the desired documents from one database to another not the design_docs.Whenever they will have to push some databases they will run this script and they will get there desired results without breaking anything.
