### ISSUE TITLE
Search Error: Multiple Keywords Still Shows OR, not AND Results

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#92]
Original Requested Update: Change the search features so that boolean language AND is used instead of OR when more than one word or field is searched.

QA done on v0.11.57 on new.qa.ole.org, old.qa.ole.org, and TRAVEL community - all showed same results, as shown below.

Searching in v0.11.57 still does not return AND results for two keywords searched (only one result should be shown):
![03_african_sister_error](https://cloud.githubusercontent.com/assets/7746327/9477259/60ff0862-4b3f-11e5-9f0f-079827178d33.JPG)

However, one thing that *has* been resolved in this version, is that one keyword plus one dropdown menu selection now uses AND instead of OR:
![02_african_dropdown_good](https://cloud.githubusercontent.com/assets/7746327/9477319/b36abd94-4b3f-11e5-89bb-9706a76f4a5e.JPG)

**Comment by MWakas** [comment]
The issue is resolved and will be given in the 0.11.58 release.Hopefully these screenshots contained the same results as you want.
![and_multiple_keywords](https://cloud.githubusercontent.com/assets/10882476/9518744/d66ee22c-4cd2-11e5-9b5a-729034b4f601.png)
![and_multiple_keywords1](https://cloud.githubusercontent.com/assets/10882476/9518745/d67df73a-4cd2-11e5-9c0e-8fe09c98cee0.png)
![and_multiple_keywords2](https://cloud.githubusercontent.com/assets/10882476/9518746/d69e07be-4cd2-11e5-8c33-c5818032f6da.png)

**Comment by treehouse-su** [comment]
to check with
https://github.com/open-learning-exchange/BeLL-Apps/commit/57ed8ad98a11119e3120bfb1d02e93416e98e992
